### ISSUE TITLE
sub dividir rutas

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#13]
Ya teniendo tres rutas de productos capaz mejor ya ir subdividiendo rutas. Una buena opción es que vayan a products y de ahí a cart, detail y add. Quedarían entonces

```
/products/cart
/products/:id (noten que no es necesario detail en el fondo ya que hay que parametrizar)
/products/add
```

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/829600161656cdb936244bb0a5c09b3677b83e61/src/routes/main-router.js#L10-L12

**Comment by pauengraff** [comment]
Resolvimos el issue.
