### ISSUE TITLE
Agregar hipervinculos

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#14]
Sería bueno que agregaran los hipervinculos para que ir linkeando las distintas secciones de la página. Eso les va a hacer más fácil la navegación además que les va ayudar a ver si el flujo de la aplicación funciona.

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/829600161656cdb936244bb0a5c09b3677b83e61/src/views/partials/header.ejs#L22-L24

**Comment by GeraZorzoni** [comment]
buenas tardes! todos los hipervinculos funcionando. sds
