### ISSUE TITLE
Sobrepoblación de datos

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-08#24]
Si bien han logrado pasar por distintas funcionalidades, sus productos quedan almacenados con algunos inconvenientes
https://github.com/0623CIFSNCN05LAED/grupo-08/blob/4810acc4eea75d25e1ad78616fad770c227ebbdb/src/data/products/productsDataBase.json#L2-L18
Por un lado, tienen un ID y un SKU manual, lo cual no parece estar teniendo un sentido concreto, el SKU podría obviarse durante la carga (y no almacenarse).
Por el otro, tienen un logo y una imagen, pero parecen estar indicando lo mismo, salvo que el logo siempre es default-logo.jpg, en este caso, si siempre es el mismo valor, sería algo que no debería almacenarse en una base de datos. Aunque en este caso no parece tener sentido su existencia, en caso de tener algún fin concreto, asegurense de poder modificar ese valor durante la carga.

Por esta misma línea, les sugiero que vayan pensando en como podrán llevar semejante cantidad de información a MySQL, hay una cantidad de datos que puede llevar algo de trabajo trasladar pero que requieren una planificación previa.

**Comment by GeraZorzoni** [comment]
Gracias Aylu, ya trabajamos sobre el tema y redujimos la cantidad de datos para los productos. los logos los vamos  manejar de distinta manera. Saludos
