### ISSUE TITLE
Vistas desconectadas

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-08#25]
Tanto la ruta de creación como de detalle de producto se encuentran aisladas.
En cuanto a la creación, se sugeriría añadir algún botón (en algún lugar que tenga sentido y sea visible)
Respecto al detalle de producto, la sugerencia sería que modificaran las tarjetas individuales y les pusieran el href de un enlace para que apuntara a su detalle particular
https://github.com/0623CIFSNCN05LAED/grupo-08/blob/4810acc4eea75d25e1ad78616fad770c227ebbdb/src/views/partials/productCard.ejs#L1-L15
Por fuera de su desconexión, es importante resaltar que están bien implementadas las funcionalidades!

**Comment by GeraZorzoni** [comment]
Buenas! se corrijen las funcionalidades para que tengan acceso tanto al detalle del productos, como en la creacion del productos. Gracias
