### ISSUE TITLE
Validación innecesaria

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#50]
Este campo no existe en el register por lo que siempre viene empty y por eso siempre da como que hay error en la validación

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/fb68b34b274f1d2fa34fa39a1173f191bf109563/src/validation/validation-register.js#L14

**Comment by GeraZorzoni** [comment]
Gracias luis, en realidad la validacion es necesaria pero en algun push ese campo del formulario de registro se borro, ahora correji la vista del formulario del registro y funciona todo ok, gracias por la ayuda!
