### ISSUE TITLE
Permite elegir roles

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#66]
Es muy raro que te deje elegir el rol, por ejemplo el de admin!! 
Por otro lado, el guest no es un usuario no registrado? por qué te deja elegir guest como rol al registrarte?

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/edb6415f796784b6c98e950e689d83e0834abe0a/src/views/users/register.ejs#L62

**Comment by GeraZorzoni** [comment]
Corregimos la logica, por default todo usuario creado va tener rol "User" , y solo el administrador puedo cambiar el rol de otro usuario para que sea admin
