### ISSUE TITLE
Editar sólo debería estar disponible apra admins

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#67]
El botón de editar, al igual que el de eliminar deberían ser sólo visibles para los administradores. 

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/edb6415f796784b6c98e950e689d83e0834abe0a/src/views/products/detailById.ejs#L30

**Comment by GeraZorzoni** [comment]
buenas tardes! Issue corregido, Gracias!
