### ISSUE TITLE
Botón de agregar

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#68]
Es algo raro que el botón de agregar esté dentro de cada producto. 
Sólo lo debería ver el admin

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/edb6415f796784b6c98e950e689d83e0834abe0a/src/views/products/detailById.ejs#L33

**Comment by GeraZorzoni** [comment]
Buenas tardes! ya solo lo puede visualizar el admin, estamos evaluando otra estructura de esos botones. Gracias
