### ISSUE TITLE
Precargar dato en editar producto

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-08#69]
A ambos loops le falta que venga seleccionado la marca y categoría del producto que se está editando

https://github.com/0623CIFSNCN05LAED/grupo-08/blob/edb6415f796784b6c98e950e689d83e0834abe0a/src/views/products/productEdit.ejs#L42-L50

**Comment by GeraZorzoni** [comment]
Buenas tardes! Issue solcionado. Precarga de datos faltantes ok
